//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoQuoteLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelYearMake
    {
        public string MODEL_ID { get; set; }
        public string YEAR_VER1 { get; set; }
        public string MAKE_VER1 { get; set; }
        public string MODEL_VER1 { get; set; }
        public string BODY_VER1 { get; set; }
        public string DESCRIPTION_VER1 { get; set; }
        public string YEAR { get; set; }
    }
}
