//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoQuoteLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteViolation
    {
        public int PRIME_KEY { get; set; }
        public int PRIME_KEY_I { get; set; }
        public string QM_VIOLATION_ID { get; set; }
        public short QM_DRIV_NO_OF_VIOL { get; set; }
        public short QM_VIOLATION_NO { get; set; }
        public Nullable<short> QM_VIOL_INCIDENT_NO { get; set; }
        public Nullable<short> QM_VIOLATION_TYPE { get; set; }
        public Nullable<short> QM_VIOLATION_RATING_TYPE { get; set; }
        public Nullable<short> QM_VIOL_CHARGED_TEST { get; set; }
        public Nullable<int> QM_DATE_OF_VIOL { get; set; }
        public Nullable<int> QM_DATE_OF_CHARGE_VIOL { get; set; }
        public string QM_VIOL_REF_NO { get; set; }
        public string QM_VIOL_SOURCE { get; set; }
    }
}
