//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoQuoteLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteAccident
    {
        public int PRIME_KEY { get; set; }
        public int PRIME_KEY_A { get; set; }
        public string QM_ACCIDENT_NO { get; set; }
        public short QM_DRIV_NO_OF_ACC_COMP { get; set; }
        public Nullable<short> QM_ACC_COMP_NO { get; set; }
        public Nullable<short> QM_ACC_COMP_IN_NO { get; set; }
        public Nullable<short> QM_SDIP_ACC_COMP { get; set; }
        public Nullable<short> QM_INJURY_ACC_COMP { get; set; }
        public Nullable<short> QM_ACCIDENT_RATING_TYPE { get; set; }
        public Nullable<short> QM_ACC_COMP_CHARGED_TEST { get; set; }
        public Nullable<int> QM_AMT_OF_ACC_COMP { get; set; }
        public Nullable<int> QM_DATE_OF_ACC_COMP { get; set; }
        public Nullable<int> QM_DATE_OF_CHARGE_ACC_COMP { get; set; }
        public string QM_ACC_COMP_REF_NO { get; set; }
        public string QM_ACC_COMP_SOURCE { get; set; }
        public Nullable<int> QM_ACC_COMP_LOAD_DATE { get; set; }
        public Nullable<int> QM_AMT_OF_ACC_UPDATE { get; set; }
        public Nullable<int> qm_coll_paid_amt { get; set; }
    }
}
