//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoQuoteLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteDriver
    {
        public int PRIME_KEY { get; set; }
        public int PRIME_KEY_D { get; set; }
        public string QM_DRIVER_NO { get; set; }
        public string QM_DRIV_FIRST { get; set; }
        public string QM_DRIV_MIDDLE { get; set; }
        public string QM_DRIV_LAST { get; set; }
        public string QM_DRIV_LICENSE { get; set; }
        public Nullable<short> QM_VEH_OF_DRIV { get; set; }
        public Nullable<short> QM_DRIV_SEX { get; set; }
        public Nullable<short> QM_DRIV_MARRIED_SINGLE { get; set; }
        public Nullable<short> QM_DRIV_TRAINING_TEST { get; set; }
        public Nullable<short> QM_OPERATOR_TYPE { get; set; }
        public Nullable<short> QM_NON_DRINK_SMOKE_TEST { get; set; }
        public Nullable<short> QM_MATURE_DRIV_TYPE { get; set; }
        public Nullable<short> QM_LL_3_TEST { get; set; }
        public Nullable<short> QM_EDUCATION_TEST { get; set; }
        public Nullable<short> QM_OCCUPATION_NO { get; set; }
        public Nullable<short> QM_OCCUPATION_CAT { get; set; }
        public Nullable<short> QM_RELATION_TO_RESP { get; set; }
        public Nullable<short> QM_DRIV_LIC_STATE_NO { get; set; }
        public Nullable<short> QM_FINANCIAL_RESP_STATE_NO { get; set; }
        public Nullable<short> QM_FINANCIAL_RESP_TEST { get; set; }
        public Nullable<short> QM_GOOD_DRIV_TEST { get; set; }
        public Nullable<short> QM_YOUTH_GROUP_TEST { get; set; }
        public Nullable<short> QM_DRIVER_STATUS { get; set; }
        public Nullable<int> QM_BIRTH_DATE_OF_DRIV { get; set; }
        public Nullable<int> QM_DATE_LICENSED { get; set; }
        public Nullable<int> QM_FINANCIAL_RESP_DATE { get; set; }
        public Nullable<int> QM_GOOD_STUDENT_DATE { get; set; }
        public Nullable<int> QM_DDC_DATE { get; set; }
        public Nullable<int> QM_MATURE_DRIV_DATE { get; set; }
        public Nullable<int> QM_DRUG_AND_ALCOHOL_DATE { get; set; }
        public Nullable<int> QM_MVR_RETURN_DATE { get; set; }
        public Nullable<short> QM_MATURE_DRIVER_DIS { get; set; }
        public Nullable<short> QM_GOOD_DRIVER_DIS { get; set; }
        public Nullable<short> QM_DDC_DISCOUNT { get; set; }
        public Nullable<short> QM_NON_DRNK_SMK_DIS { get; set; }
        public Nullable<short> QM_DRIV_TRAINING_DIS { get; set; }
        public Nullable<short> QM_GOOD_STUDENT_DIS { get; set; }
        public Nullable<short> QM_AWAY_SCHOOL_DIS { get; set; }
        public Nullable<short> QM_COLLEGE_GRAD_DIS { get; set; }
        public Nullable<short> QM_YOUTH_GROUP_DIS { get; set; }
        public Nullable<short> QM_DRUG_ALCOHOL_DIS { get; set; }
        public Nullable<int> QM_DRIVER_ADDED_DATE { get; set; }
        public Nullable<int> QM_CLUE_LAST_ORDER_DATE { get; set; }
        public Nullable<int> QM_CLUE_NEXT_ORDER_DATE { get; set; }
        public Nullable<int> QM_CLUE_OVERRIDE_ORDER_DATE { get; set; }
        public Nullable<short> QM_CLUE_OVERRIDE_YN { get; set; }
        public Nullable<int> QM_MVR_LAST_ORDER_DATE { get; set; }
        public Nullable<int> QM_MVR_NEXT_ORDER_DATE { get; set; }
        public Nullable<int> QM_MVR_OVERRIDE_ORDER_DATE { get; set; }
        public Nullable<short> QM_MVR_OVERRIDE_YN { get; set; }
        public Nullable<short> QM_ORIG_DRIVER_NO { get; set; }
        public string QM_SOC_SEC_NUMBER { get; set; }
        public Nullable<short> QM_DRIV_SDIP_POINTS { get; set; }
        public Nullable<short> QM_EMPLOYMENT_STATUS { get; set; }
        public Nullable<short> QM_age_first_licensed_yrs { get; set; }
        public Nullable<short> QM_age_first_licensed_months { get; set; }
        public Nullable<short> QM_DRIV_SDIP_POINTS_BI { get; set; }
        public Nullable<short> QM_DRIV_SDIP_POINTS_PD { get; set; }
        public Nullable<short> QM_DRIV_SDIP_POINTS_PIP { get; set; }
        public Nullable<short> QM_DRIV_SDIP_POINTS_UMBI { get; set; }
        public Nullable<short> QM_DRIV_SDIP_POINTS_UMPD { get; set; }
        public Nullable<short> QM_DRIV_SDIP_POINTS_PPI { get; set; }
        public Nullable<short> QM_DRIV_SDIP_POINTS_OTC { get; set; }
        public Nullable<short> QM_DRIV_SDIP_POINTS_COLL { get; set; }
        public Nullable<short> QM_DRIVER_LICENSE_STATUS { get; set; }
        public Nullable<short> QM_DRIVER_EXCLUSION_STATUS { get; set; }
        public byte[] qm_soc_sec_number_enc { get; set; }
        public Nullable<short> QM_CLEAN_COVD_DIS { get; set; }
    }
}
