//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoQuoteLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_web_state_zip_ranges
    {
        public int PRIME_KEY { get; set; }
        public string state { get; set; }
        public Nullable<int> min_zip { get; set; }
        public Nullable<int> max_zip { get; set; }
    }
}
