//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoQuoteLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int PRIME_KEY { get; set; }
        public string VO_MD_YEAR { get; set; }
        public string VO_YEAR { get; set; }
        public string VO_MODEL_ID { get; set; }
        public string VO_YEAR1 { get; set; }
        public string VO_MAKE_NO { get; set; }
        public string VO_MAKE_CODE { get; set; }
        public string VO_VIN_NO { get; set; }
        public string VO_IIN_CENTURY { get; set; }
        public string VO_IIN_YEAR { get; set; }
        public string VO_IIN_NO { get; set; }
        public string VO_MODEL { get; set; }
        public string VO_BODY { get; set; }
        public string VO_DESCRIPTION { get; set; }
        public string VO_RESTRAINT { get; set; }
        public string VO_ANTI_LOCK_BRAKE { get; set; }
        public string VO_WHEELS_DRIVEN { get; set; }
        public string VO_SPECIAL_INFO { get; set; }
        public string VO_DAYTIME_LIGHTS_TEST { get; set; }
        public string VO_ANTI_THEFT_INFO { get; set; }
        public string VO_OLD_FLAG { get; set; }
        public Nullable<short> VO_SYMBOL { get; set; }
        public Nullable<short> VO_SYMBOL_2 { get; set; }
        public Nullable<short> VO_SYMBOL_3 { get; set; }
        public Nullable<short> VO_SYMBOL_4 { get; set; }
        public Nullable<short> VO_SYMBOL_5 { get; set; }
        public Nullable<short> VO_SYMBOL_6 { get; set; }
        public Nullable<short> VO_SYMBOL_7 { get; set; }
        public Nullable<short> VO_SYMBOL_8 { get; set; }
        public Nullable<short> VO_SYMBOL_9 { get; set; }
        public Nullable<short> VO_SYMBOL_10 { get; set; }
        public Nullable<short> VO_COST_NEW { get; set; }
        public Nullable<short> VO_VEH_TYPE { get; set; }
        public Nullable<short> VO_EXPOSURE { get; set; }
        public Nullable<short> VO_SAFE_VEHICLE { get; set; }
        public Nullable<short> VO_PERFORMANCE { get; set; }
        public Nullable<short> VO_SYMBOL_EXCEPTION { get; set; }
        public Nullable<short> VO_SEAT_BELTS { get; set; }
        public Nullable<short> VO_AIR_BAG { get; set; }
        public Nullable<short> VO_ABS { get; set; }
        public Nullable<short> VO_DRL { get; set; }
        public Nullable<short> VO_ANTI_THEFT { get; set; }
        public Nullable<short> VO_4_DOOR { get; set; }
        public Nullable<short> VO_INELIGIBLE_VEH_TYPE { get; set; }
        public string VO_ADJUST_TO_MAKE_MODEL { get; set; }
        public Nullable<short> VO_SOURCE { get; set; }
        public Nullable<int> VO_DATE_ADDED { get; set; }
        public string vo_year_make_model { get; set; }
        public string VO_WEB_MODEL { get; set; }
    }
}
