//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoQuoteLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class YearMake
    {
        public int prime_key { get; set; }
        public string mk_year { get; set; }
        public string MK_NUMBER_VER { get; set; }
        public string MK_DESCRIP { get; set; }
    }
}
